gpu_id: "0,1,2,3,4,5,6,7"
retrieval_method: "e5"
retrieval_model_path: "/mnt/public/data/lh/yqj/model/e5-base-v2"
index_path: "/mnt/public/data/lh/yqj/TaskCraft/src/tools/FlashRAG/retrieval_corpus/data00/jiajie_jin/flashrag_indexes/wiki_dpr_100w/e5_flat_inner.index" 
faiss_gpu: False
corpus_path: "/mnt/public/data/lh/yqj/TaskCraft/src/tools/FlashRAG/retrieval_corpus/wiki18_100w.jsonl"  